# Site settings
title: 개발자 이수현의 포트폴리오입니다.
description: Jekyll Theme Minimal Resume
# baseurl: ""
# url: ""

# User settings
username: Lee Suhyun
user_title: Software Engineer
email: a94460093@gmail.com
github_username:  lshyunee