# Site settings
title: Mauricio Urraco
description: Jekyll Theme Minimal Resume
baseurl: "https://fake-whiteboy.tistory.com/"
url: "lshyunee.github.io"

# User settings
username: Lee Suhyun
user_title: Software Engineer
email: a94460093@gmail.com
github_username:  lshyunee